### ISSUE TITLE
port forwarding

### ISSUE THREAD

**Issue by joedupa** [i3roly/glibc_ddwrt#15] opened 2022-11-02 20:15 UTC
Hello, port forwarding from a specific source IP doesn't work. I want to restrict access to port 80 on the route, and port 22 on the internal machine to the specific source IP only from two of my static IP source at home and at work. This works in the official dd-wrt builds, which for obvious reasons I don't want to use. Could you please assist?
Thanks a lot.
<img width="1087" alt="Screen Shot 2022-11-02 at 16 17 02" src="https://user-images.githubusercontent.com/12486073/199594766-3c2bd300-895c-4aaa-ae83-a7eccb875967.png">

**Comment by i3roly** [comment] 2022-11-03 00:30
what i would do, is compare the iptables rules from a working build to my build.

they shouldn't be any different, but that should help determine the problem.

i personally havent' changed anything in the firewall code.

**Comment by i3roly** [comment] 2022-11-08 15:24
again another false ticket without any followup or troubleshooting.

closing ticket because i don't know how this person would have this problem

**Closed by i3roly** 2022-11-08 15:24 UTC

**Comment by joedupa** [comment] 2022-11-09 14:26
Thanks for your answer. I have two identical routers (Dlink DIR-882 A1) one with dd-wrt and another with your software. Again, I want to allow access to the router exclusively from a single internet IP of one of my remote servers, and forward the specific "Port from" (25980) to the internal machine on port 80. I enter this under NAT/QoS and Port Forwarding. On both routers the settings are identical. This works on the router with dd-wrt, but not on the router with your software. When I ssh and issue the following command: 
iptables -t nat -L
the router with your latest version of software comes up with empty entries for iptables, please let me know if this can be fixed. Thanks!!


<img width="791" alt="Screen Shot 2022-11-09 at 10 10 16" src="https://user-images.githubusercontent.com/12486073/200855190-c535a159-d69b-4268-b78a-e43f6f35c88c.png">


<img width="1077" alt="Screen Shot 2022-11-09 at 10 21 36" src="https://user-images.githubusercontent.com/12486073/200855239-452d2881-8ef4-44b1-890a-d08ca8fab561.png">



<img width="682" alt="Screen Shot 2022-11-09 at 10 10 49" src="https://user-images.githubusercontent.com/12486073/200855325-c0f55101-e7ed-4c9d-829b-c8c70bf5accf.png">


<img width="394" alt="Screen Shot 2022-11-09 at 10 11 12" src="https://user-images.githubusercontent.com/12486073/200855397-81823dbc-d97f-4ec7-9594-37dfda0fb7e8.png">

**Comment by joedupa** [comment] 2022-11-09 14:28
I am sorry for late reply, I was travelling. Could you please reopen this issue and see if this can be resolved?

**Comment by i3roly** [comment] 2022-11-09 14:33
Of course it's not going to work when you have no WAN IP on my build!!

How can iptables forward from an address that doesn't exist!?

From: joedupa
Sent: Wednesday, 9 November 2022 7:28 AM
To: i3roly/glibc_ddwrt
Reply To: i3roly/glibc_ddwrt
Cc: gagan sidhu; State change
Subject: Re: [i3roly/glibc_ddwrt] port forwarding (Issue #15)


I am sorry for late reply, I was travelling. Could you please reopen this issue and see if this can be resolved?

**Comment by i3roly** [comment] 2022-11-09 14:38
You shouldn't be using 759 anyways since it can't update wireless settings.

Your issue is not having a wan IP. This is painfully obvious in the iptables output with no entries.

"My software" is dd-wrt using glibc. Right now the issue isn't anything to do with port forwarding.

You should be asking why you don't have a wan IP, and telling me what kind of WAN you have? Pppoe or something?

From: joedupa
Sent: Wednesday, 9 November 2022 7:28 AM
To: i3roly/glibc_ddwrt
Reply To: i3roly/glibc_ddwrt
Cc: gagan sidhu; State change
Subject: Re: [i3roly/glibc_ddwrt] port forwarding (Issue #15)


I am sorry for late reply, I was travelling. Could you please reopen this issue and see if this can be resolved?

**Comment by i3roly** [comment] 2022-11-09 14:42
Also: you're using an OLD build of BS'. Four years old. I assume it's using mt_wifi driver.

It sounds to me like you use pppoe or some kind of station mode to connect to the internet. Only the latest builds have 8021x. I didn't have them in my builds before 50813.

If you're relying on station mode 8021x or something like that, 50579‎ won't work. This would be why you don't have wan, and why forwarding wouldn't work.
