### ISSUE TITLE
DIR-3040 router username/password outright not working, and GUI access not disabling

### ISSUE THREAD

**Issue by lifehackerhansol** [i3roly/glibc_ddwrt#14] opened 2022-05-28 10:24 UTC
As this is the first time I've ever ran DD-WRT of any sort, I am unsure what to expect.

So far, model DIR-3040. I have freshly installed factory-to-ddwrt-se.bin with the latest commit as of this writing (0be4c905a6c2ed34b76dddc808fc86df491df899). Nothing other than official firmware had been flashed before.

I tried to enable what would be equivalent of a "guest network" by adding a VAP to wl0 (2.4ghz), enabled net isolation and AP isolation. This worked.

I then tried to disable Wireless GUI access. This... didn't work. In fact, it doesn't even work on the regular APs. I figured there was some way to add a VLAN to get around that issue but I couldn't find the VAP in the second DHCP that I created. So that hasn't been touched since.

While trying to figure out what was wrong, I accidentally typed the wrong password while logging into the web GUI, and this worked. It was the wrong password. Was baffled, so I cleared my history and tried again with and just mashed the keyboard, also let me into the whole GUI. 

Now if the GUI could be disabled for the guest network (or any network for that matter) I would not have minded the password issue, but both of them together seems like a security nightmare. According to some forum posts this feature is not available on all models, which seems slightly odd but I'll take it. But then it would have been nice if the password wasn't basically transparent...

Steps to reproduce GUI disabling issue:
1. Wireless Settings -> Basic
1. Disable Wireless GUI Access
1. Save
1. Apply changes
1. See that you can still open router GUI

Steps to reproduce password not working:
1. Clear all browsing history on a Wi-Fi client
1. Open GUI and go to any tab
1. When asked, type in username, and put in gibberish as password
1. See that you have access to that tab regardless

I am unsure what other info is needed. Let me know if you need anything else. I guess I'll have to work around the guest network by double-NATting for now...

**Comment by lifehackerhansol** [comment] 2022-05-29 17:47
It seems I missed a note for the laundry list in README, which the "password not working" applies.

It mentions upgrade from build 47525, but I'm on 48427. So it still hasn't been fixed, it appears.

**Comment by i3roly** [comment] 2022-08-28 16:17
i am confused.

i just came back from a time out, so i will need time to go through the issues.

as i understand it: you're stating you entered the wrong password on the webgui and obtained access?

i could not replicate this error on a DIR-882. i am certain there is no difference in the code between the 882 and 3040 in terms of the password.

**Comment by lifehackerhansol** [comment] 2022-08-28 16:47
So `root` is fine. But entering a bogus username (i.e. `admin`) and password just kinda works, from what I remember. I need to test again later tonight to double check as well.

**Comment by i3roly** [comment] 2022-08-28 19:17
i will look into that soon.

are there any performance/functional issues with the radios? do they perform reasonably well? some people from india were complaining before i had to take my time out, and i want to be sure these are real issues.

**Comment by lifehackerhansol** [comment] 2022-08-28 19:23
I haven't noticed any performance issues with the radio.

**Comment by i3roly** [comment] 2022-08-28 20:06
i have tried a random username with both an incorrect and correct password (for the root username) and neither would allow me to login.

are you sure this is an issue? i haven't tried the GUI disabling stuff yet but i just updated all of the dd-wrt code and i'm hoping that alleviates it. i will push the update soon.

**Comment by lifehackerhansol** [comment] 2022-08-28 20:12
I will check again tonight. Which is a few hours away as I'm heading to work at the moment.

**Comment by i3roly** [comment] 2022-10-25 12:20
as far as i am aware, there are no issues here.

i tested your complaint and i could not reproduce it, so i am closing

**Closed by i3roly** 2022-10-25 12:20 UTC

**Comment by i3roly** [comment] 2022-11-10 03:03
cartoon porn kid @lifehackerhansol are you still using my builds?

did you have any issues with mac addresses being read?

was going to ask if you had some time and could try the newest build w/ reset to defaults to see if it picks them up properly.

wanna know if this is simply limited to one 2640 user or all 2640/3040 people.

**Comment by i3roly** [comment] 2022-11-12 22:45
cartoon porn kid @lifehackerhansol, the "httpd bug" you were referring to was not a bug.

what you thought was "any password" is wrong. you needed the first 8 matching characters to successfully authenticate, where the rest of the password was ignored. this is a well-known attribute of DES encryption.

this will be 'fixed' in the next build. 

i will note this is not limited to my build, but any distribution that does not specifically set an encryption type using crypt_r:

https://unix.stackexchange.com/questions/415787/ssh-why-can-i-login-with-partial-passwords

i will be setting all passwords to SHA-512 in the next update so the fences protecting your fantasy trove will remain safe for a long time.

i'll note that in BS' builds he uses MD5 which is dead on arrival. the username will remain MD5 because it won't work with SHA-512. i have no idea why the username for httpd is encrypted anyways.

i hope this helps explain what you thought was a bug.

**Comment by lifehackerhansol** [comment] 2022-11-12 22:51
Thank you for explaining. That makes a lot more sense.

I will try to set up the new build this weekend. Is that MAC address thing still something you need checked?

**Comment by i3roly** [comment] 2022-11-13 00:10
nah it's fine man, it turns out the other guy was just screwing around.

________________________________
